# Generated by Django 5.0.2 on 2024-02-19 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("x_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin1",
            name="user_2",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="login",
            name="is_admin1",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="user_1",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
